# Generated by Django 5.0 on 2023-12-24 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2023, 12, 24, 8, 26, 24, 670346, tzinfo=datetime.timezone.utc)),
        ),
    ]
