# Generated by Django 5.0 on 2023-12-25 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('email_sent', 'Email Sent'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2023, 12, 25, 8, 44, 32, 275227, tzinfo=datetime.timezone.utc)),
        ),
    ]
