# Generated by Django 5.0 on 2023-12-25 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invitation_status_alter_task_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2023, 12, 25, 8, 47, 35, 450750, tzinfo=datetime.timezone.utc)),
        ),
    ]
